<a id="network-meta-analysis-using-R"></a>

<h2 align="center" style="font-family:Times New Roman;font-variant: small-caps;">Network Meta-Analysis using R</h2>

---

Step 2. Network Meta-Analysis using R

In [25]:
root <- getwd()
print(root)

[1] "G:/Shared drives/network_meta-analysis/3_meta-analysis"

In [67]:
packages <- c(
    "readr",
    "readxl",
    "meta",
    "metafor",
    "netmeta",
    "ggplot2"
)

# Uncomment to install packages the first time only.
#for (package in packages) {if (!requireNamespace(package, quietyly = TRUE)) {install.packages(package, dependencies = TRUE, quiet = TRUE)}}

# Load libraries
lapply(packages, library, character.only = TRUE)

[[1]]
 [1] "ggplot2"   "netmeta"   "metafor"   "numDeriv"  "metadat"   "Matrix"
 [7] "meta"      "metabook"  "readxl"    "readr"     "stats"     "graphics"
[13] "grDevices" "utils"     "datasets"  "methods"   "base"

[[2]]
 [1] "ggplot2"   "netmeta"   "metafor"   "numDeriv"  "metadat"   "Matrix"
 [7] "meta"      "metabook"  "readxl"    "readr"     "stats"     "graphics"
[13] "grDevices" "utils"     "datasets"  "methods"   "base"

[[3]]
 [1] "ggplot2"   "netmeta"   "metafor"   "numDeriv"  "metadat"   "Matrix"
 [7] "meta"      "metabook"  "readxl"    "readr"     "stats"     "graphics"
[13] "grDevices" "utils"     "datasets"  "methods"   "base"

[[4]]
 [1] "ggplot2"   "netmeta"   "metafor"   "numDeriv"  "metadat"   "Matrix"
 [7] "meta"      "metabook"  "readxl"    "readr"     "stats"     "graphics"
[13] "grDevices" "utils"     "datasets"  "methods"   "base"

[[5]]
 [1] "ggplot2"   "netmeta"   "metafor"   "numDeriv"  "metadat"   "Matrix"
 [7] "meta"      "metabook"  "readxl"    "readr"     "stats"     "graphics"
[13] "grDevices" "utils"     "datasets"  "methods"   "base"

[[6]]
 [1] "ggplot2"   "netmeta"   "metafor"   "numDeriv"  "metadat"   "Matrix"
 [7] "meta"      "metabook"  "readxl"    "readr"     "stats"     "graphics"
[13] "grDevices" "utils"     "datasets"  "methods"   "base"

**Custom function for running pairwise meta-analysis** using `meta` and `netmeta`.

In [68]:
pairwise_meta_analysis <- function(df, sm = "") {
    data_path <- paste0("./input/data/sheets_for_analysis/", df, ".csv")
    data <- read.csv(data_path)

    m.gen <- metagen(
        data = data,
        studlab = study,
        TE = TE,
        seTE = seTE,
        sm = paste0(sm),
        random = TRUE,
        common = FALSE,
        subgroup = subgroup
    )

    assign(paste0(df, "_pw"), m.gen, envir = .GlobalEnv)

    # Create data frame
    dat <- data.frame(
        "k" = round(m.gen$k.w, 4),
        sm = round(m.gen$TE.random.w, 4),
        "ci.lb" = round(m.gen$lower.random.w, 4),
        "ci.ub" = round(m.gen$upper.random.w, 4),
        "pval" = round(m.gen$pval.random.w, 4),
        "I^2" = round(m.gen$I2.w, 4)
    )

    write.csv(dat, paste0("./output/tables/pairwise/", df, ".csv"))
    assign(paste0(df, "_dat"), dat, envir = .GlobalEnv)
    print(dat)
}

In [70]:
continuous = c("ikdc_subjective", "lysholm", "tegner", "instrumented_laxity")
lapply(continuous, sm = "SMD", pairwise_meta_analysis)

             k     sm   ci.lb  ci.ub   pval    I.2
BPTB vs. QT  3 0.2025 -0.0781 0.4831 0.1572 0.0000
HT vs. PLT   3 0.1935 -0.0640 0.4510 0.1407 0.0000
HT vs. TA    2 0.3647 -0.2434 0.9727 0.2398 0.6961
HT vs. QT    6 0.3018  0.1197 0.4840 0.0012 0.0000
BPTB vs. HT 11 0.5025  0.0691 0.9358 0.0231 0.8018
             k     sm   ci.lb  ci.ub   pval    I.2
BPTB vs. HT 20 0.3287  0.1431 0.5143 0.0005 0.6192
BPTB vs. QT  3 0.2148 -0.0740 0.5037 0.1449 0.0000
HT vs. PLT   2 0.3879 -0.2002 0.9761 0.1961 0.5797
HT vs. QT    4 0.4218 -0.0467 0.8903 0.0777 0.7321
HT vs. TA    2 0.3963  0.1127 0.6798 0.0062 0.0000
HT vs. AT    1 0.2760 -0.2120 0.7640 0.2677     NA
             k     sm   ci.lb  ci.ub   pval    I.2
BPTB vs. HT 15 0.4982  0.2896 0.7067 0.0000 0.7488
BPTB vs. QT  1 0.0000 -0.4234 0.4234 1.0000     NA
HT vs. TA    3 0.0400 -0.1963 0.2763 0.7400 0.0000
HT vs. QT    1 0.0710 -0.3288 0.4708 0.7278     NA
HT vs. PLT   1 0.5260 -0.0385 1.0905 0.0678     NA
HT vs. AT    1 0.0000 -0.4861 0.4861 1.0000     NA
             k     sm   ci.lb  ci.ub   pval    I.2
BPTB vs. HT 26 0.2852  0.2038 0.3666 0.0000 0.0000
BPTB vs. QT  2 0.0869 -0.2647 0.4384 0.6282 0.0000
HT vs. PLT   2 0.2378 -0.0605 0.5361 0.1182 0.0000
HT vs. QT    3 0.2831 -0.0279 0.5942 0.0744 0.1599
HT vs. TA    1 0.9900  0.4706 1.5094 0.0002     NA

[[1]]
             k     sm   ci.lb  ci.ub   pval    I.2
BPTB vs. QT  3 0.2025 -0.0781 0.4831 0.1572 0.0000
HT vs. PLT   3 0.1935 -0.0640 0.4510 0.1407 0.0000
HT vs. TA    2 0.3647 -0.2434 0.9727 0.2398 0.6961
HT vs. QT    6 0.3018  0.1197 0.4840 0.0012 0.0000
BPTB vs. HT 11 0.5025  0.0691 0.9358 0.0231 0.8018

[[2]]
             k     sm   ci.lb  ci.ub   pval    I.2
BPTB vs. HT 20 0.3287  0.1431 0.5143 0.0005 0.6192
BPTB vs. QT  3 0.2148 -0.0740 0.5037 0.1449 0.0000
HT vs. PLT   2 0.3879 -0.2002 0.9761 0.1961 0.5797
HT vs. QT    4 0.4218 -0.0467 0.8903 0.0777 0.7321
HT vs. TA    2 0.3963  0.1127 0.6798 0.0062 0.0000
HT vs. AT    1 0.2760 -0.2120 0.7640 0.2677     NA

[[3]]
             k     sm   ci.lb  ci.ub   pval    I.2
BPTB vs. HT 15 0.4982  0.2896 0.7067 0.0000 0.7488
BPTB vs. QT  1 0.0000 -0.4234 0.4234 1.0000     NA
HT vs. TA    3 0.0400 -0.1963 0.2763 0.7400 0.0000
HT vs. QT    1 0.0710 -0.3288 0.4708 0.7278     NA
HT vs. PLT   1 0.5260 -0.0385 1.0905 0.0678     NA
HT vs. AT    1 0.0000 -0.4861 0.4861 1.0000     NA

[[4]]
             k     sm   ci.lb  ci.ub   pval    I.2
BPTB vs. HT 26 0.2852  0.2038 0.3666 0.0000 0.0000
BPTB vs. QT  2 0.0869 -0.2647 0.4384 0.6282 0.0000
HT vs. PLT   2 0.2378 -0.0605 0.5361 0.1182 0.0000
HT vs. QT    3 0.2831 -0.0279 0.5942 0.0744 0.1599
HT vs. TA    1 0.9900  0.4706 1.5094 0.0002     NA

In [71]:
dichotomous = c("pivot_shift_1", "pivot_shift_2", "lachman_1", "lachman_2", "graft_failure")
lapply(dichotomous, sm = "OR", pairwise_meta_analysis)

             k      sm   ci.lb   ci.ub   pval    I.2
BPTB vs. HT 15 -0.5237 -0.8698 -0.1777 0.0030 0.1512
HT vs. PLT   2 -0.0005 -0.9870  0.9861 0.9993 0.0000
HT vs. QT    3  0.5437 -0.4633  1.5507 0.2900 0.0000
HT vs. TA    3 -0.4096 -1.0113  0.1921 0.1822 0.2962
BPTB vs. QT  1 -1.0300 -2.4804  0.4204 0.1639     NA
HT vs. AT    1 -0.8210 -1.9382  0.2962 0.1498     NA
             k      sm   ci.lb  ci.ub   pval I.2
BPTB vs. HT 15  0.0345 -0.4687 0.5377 0.8932   0
HT vs. PLT   2  0.4466 -0.9272 1.8204 0.5241   0
HT vs. QT    3  0.3970 -1.7171 2.5112 0.7128   0
HT vs. TA    3 -0.2570 -1.6001 1.0862 0.7077   0
BPTB vs. QT  1 -1.0300 -2.4804 0.4204 0.1639  NA
HT vs. AT    1 -0.9467 -2.9244 1.0309 0.3481  NA
             k      sm   ci.lb  ci.ub   pval    I.2
BPTB vs. HT 15 -0.3236 -0.6531 0.0059 0.0542 0.3839
HT vs. TA    2 -0.4555 -1.3887 0.4776 0.3387 0.5356
HT vs. PLT   1  0.3812 -1.3436 2.1059 0.6649     NA
HT vs. AT    1 -0.0377 -1.2509 1.1755 0.9514     NA
             k      sm   ci.lb  ci.ub   pval I.2
BPTB vs. HT 15  0.2223 -0.3599 0.8044 0.4543   0
HT vs. TA    2 -0.5371 -1.5299 0.4558 0.2891   0
HT vs. PLT   1  0.3812 -1.3436 2.1059 0.6649  NA
HT vs. AT    1 -0.9467 -2.9244 1.0309 0.3481  NA
             k      sm   ci.lb  ci.ub   pval I.2
BPTB vs. HT 11 -0.1962 -0.5691 0.1767 0.3025   0
HT vs. QT    1  1.0399 -2.1960 4.2758 0.5288  NA

[[1]]
             k      sm   ci.lb   ci.ub   pval    I.2
BPTB vs. HT 15 -0.5237 -0.8698 -0.1777 0.0030 0.1512
HT vs. PLT   2 -0.0005 -0.9870  0.9861 0.9993 0.0000
HT vs. QT    3  0.5437 -0.4633  1.5507 0.2900 0.0000
HT vs. TA    3 -0.4096 -1.0113  0.1921 0.1822 0.2962
BPTB vs. QT  1 -1.0300 -2.4804  0.4204 0.1639     NA
HT vs. AT    1 -0.8210 -1.9382  0.2962 0.1498     NA

[[2]]
             k      sm   ci.lb  ci.ub   pval I.2
BPTB vs. HT 15  0.0345 -0.4687 0.5377 0.8932   0
HT vs. PLT   2  0.4466 -0.9272 1.8204 0.5241   0
HT vs. QT    3  0.3970 -1.7171 2.5112 0.7128   0
HT vs. TA    3 -0.2570 -1.6001 1.0862 0.7077   0
BPTB vs. QT  1 -1.0300 -2.4804 0.4204 0.1639  NA
HT vs. AT    1 -0.9467 -2.9244 1.0309 0.3481  NA

[[3]]
             k      sm   ci.lb  ci.ub   pval    I.2
BPTB vs. HT 15 -0.3236 -0.6531 0.0059 0.0542 0.3839
HT vs. TA    2 -0.4555 -1.3887 0.4776 0.3387 0.5356
HT vs. PLT   1  0.3812 -1.3436 2.1059 0.6649     NA
HT vs. AT    1 -0.0377 -1.2509 1.1755 0.9514     NA

[[4]]
             k      sm   ci.lb  ci.ub   pval I.2
BPTB vs. HT 15  0.2223 -0.3599 0.8044 0.4543   0
HT vs. TA    2 -0.5371 -1.5299 0.4558 0.2891   0
HT vs. PLT   1  0.3812 -1.3436 2.1059 0.6649  NA
HT vs. AT    1 -0.9467 -2.9244 1.0309 0.3481  NA

[[5]]
             k      sm   ci.lb  ci.ub   pval I.2
BPTB vs. HT 11 -0.1962 -0.5691 0.1767 0.3025   0
HT vs. QT    1  1.0399 -2.1960 4.2758 0.5288  NA

**Custom function for running network meta-analysis** using `netmeta`.

In [76]:
network_meta_analysis <- function(df, sm, reference = "", backtransf = FALSE) {
    
    data_path <- paste0(root, "/input/data/sheets_for_analysis/", df, ".csv")
    data <- read.csv(data_path)
    
    m.netmeta <- netmeta(
        data = data,
        studlab = study,
        TE = TE,
        treat1 = treat1,
        treat2 = treat2,
        seTE = seTE,
        sm = paste0(sm),
        reference.group = paste0(reference),
        random = TRUE,
        common = FALSE,
        backtransf = TRUE,
        sep.trts = " vs. "
        )
    
    # results (netmeta, decomp.design, netsplit, netleague, netrank)
    sink(file = paste0("./output/results/netmeta/", df, ".txt"))
    print(m.netmeta)
    sink()

    sink(file = paste0("./output/results/decomp/", df, ".txt"))
    decomp <- decomp.design(m.netmeta)
    print(decomp)
    sink()

    sink(file = paste0("./output/results/netsplit/", df, ".txt"))
    netsplit <- netsplit(m.netmeta)
    print(netsplit)
    sink()

    sink(file = paste0("./output/results/netrank/", df, ".txt"))
    netrank <- netrank(m.netmeta,
                        method = "SUCRA",
                        nsim = 10000,
                        small.values = "bad"
                       )
    print(netrank)
    sink()

    order =  c("BPTB", "HT", "QT", "PLT", "AT", "TA")
    seq = order[order %in% m.netmeta$trts]
        
    netleague <- netleague(m.netmeta,
                           bracket = "[",
                           digits = 3,
                           details = TRUE,
                           seq = seq
                           )
    write.csv(netleague$random, paste0("./output/results/netleague/", df, ".csv"))
    
    # plots
    file <- paste0("./output/plots/forest/", df, ".svg")
    svg(file = file, width = 1200, height = 800)
    forest(m.netmeta)
    dev.off()

    assign(paste0(df), m.netmeta, envir = .GlobalEnv)

    dat <- data.frame(
        "k" = round(m.netmeta$k, 4),
        "TE" = round(m.netmeta$TE.random, 4),
        "ci.lb" = round(m.netmeta$lower.random, 4),
        "ci.ub" = round(m.netmeta$upper.random, 4),
        "pval" = round(m.netmeta$pval.random, 4)
    )
    
    write.csv(dat, paste0("./output/tables/network/", df, ".csv"))
    print(dat)    
#    assign(paste0(df, "_league"), netleague, envir = .GlobalEnv)
#    assign(paste0(df, "_rank"), netrank, envir = .GlobalEnv)
#    print(m.netmeta)
#    print(netleague)

}

**Network meta-analysis** for continuous outcomes

In [77]:
continuous = c("ikdc_subjective", "lysholm", "tegner", "instrumented_laxity")
lapply(continuous, sm = "SMD", reference = "BPTB", network_meta_analysis)

      k TE.BPTB   TE.HT  TE.PLT   TE.QT  TE.TA ci.lb.BPTB ci.lb.HT ci.lb.PLT
BPTB 25  0.0000  0.3601  0.5800  0.5326 0.7234     0.0000   0.1215    0.0519
HT   25 -0.3601  0.0000  0.2198  0.1725 0.3633    -0.5988   0.0000   -0.2512
PLT  25 -0.5800 -0.2198  0.0000 -0.0473 0.1434    -1.1080  -0.6909    0.0000
QT   25 -0.5326 -0.1725  0.0473  0.0000 0.1908    -0.8538  -0.4633   -0.5062
TA   25 -0.7234 -0.3633 -0.1434 -0.1908 0.0000    -1.3482  -0.9406   -0.8886
     ci.lb.QT ci.lb.TA ci.ub.BPTB ci.ub.HT ci.ub.PLT ci.ub.QT ci.ub.TA
BPTB   0.2115   0.0987     0.0000   0.5988    1.1080   0.8538   1.3482
HT    -0.1183  -0.2141    -0.1215   0.0000    0.6909   0.4633   0.9406
PLT   -0.6009  -0.6017    -0.0519   0.2512    0.0000   0.5062   0.8886
QT     0.0000  -0.4557    -0.2115   0.1183    0.6009   0.0000   0.8372
TA    -0.8372   0.0000    -0.0987   0.2141    0.6017   0.4557   0.0000
     pval.BPTB pval.HT pval.PLT pval.QT pval.TA
BPTB       NaN  0.0031   0.0313  0.0012  0.0232
HT      0.0031     NaN   0.3604  0.2450  0.2175
PLT     0.0313  0.3604      NaN  0.8669  0.7060
QT      0.0012  0.2450   0.8669     NaN  0.5630
TA      0.0232  0.2175   0.7060  0.5630     NaN
      k   TE.AT TE.BPTB   TE.HT TE.PLT   TE.QT   TE.TA ci.lb.AT ci.lb.BPTB
AT   32  0.0000 -0.5578 -0.2760 0.1094 -0.0568  0.0982   0.0000    -1.3109
BPTB 32  0.5578  0.0000  0.2818 0.6672  0.5010  0.6560  -0.1953     0.0000
HT   32  0.2760 -0.2818  0.0000 0.3854  0.2192  0.3742  -0.4599    -0.4420
PLT  32 -0.1094 -0.6672 -0.3854 0.0000 -0.1662 -0.0112  -1.0247    -1.2347
QT   32  0.0568 -0.5010 -0.2192 0.1662  0.0000  0.1550  -0.7347    -0.7998
TA   32 -0.0982 -0.6560 -0.3742 0.0112 -0.1550  0.0000  -0.9813    -1.1699
     ci.lb.HT ci.lb.PLT ci.lb.QT ci.lb.TA ci.ub.AT ci.ub.BPTB ci.ub.HT
AT    -1.0119   -0.8060  -0.8483  -0.7849   0.0000     0.1953   0.4599
BPTB   0.1217    0.0997   0.2022   0.1421   1.3109     0.0000   0.4420
HT     0.0000   -0.1591  -0.0723  -0.1141   1.0119    -0.1217   0.0000
PLT   -0.9298    0.0000  -0.7837  -0.7425   0.8060    -0.0997   0.1591
QT    -0.5106   -0.4513   0.0000  -0.4136   0.8483    -0.2022   0.0723
TA    -0.8625   -0.7201  -0.7236   0.0000   0.7849    -0.1421   0.1141
     ci.ub.PLT ci.ub.QT ci.ub.TA pval.AT pval.BPTB pval.HT pval.PLT pval.QT
AT      1.0247   0.7347   0.9813     NaN    0.1466  0.4623   0.8149  0.8881
BPTB    1.2347   0.7998   1.1699  0.1466       NaN  0.0006   0.0212  0.0010
HT      0.9298   0.5106   0.8625  0.4623    0.0006     NaN   0.1653  0.1405
PLT     0.0000   0.4513   0.7201  0.8149    0.0212  0.1653      NaN  0.5979
QT      0.7837   0.0000   0.7236  0.8881    0.0010  0.1405   0.5979     NaN
TA      0.7425   0.4136   0.0000  0.8275    0.0123  0.1331   0.9761  0.5932
     pval.TA
AT    0.8275
BPTB  0.0123
HT    0.1331
PLT   0.9761
QT    0.5932
TA       NaN
      k   TE.AT TE.BPTB   TE.HT TE.PLT   TE.QT   TE.TA ci.lb.AT ci.lb.BPTB
AT   22  0.0000 -0.4781  0.0000 0.5260 -0.1991  0.0521   0.0000    -1.3196
BPTB 22  0.4781  0.0000  0.4781 1.0041  0.2790  0.5303  -0.3633     0.0000
HT   22  0.0000 -0.4781  0.0000 0.5260 -0.1991  0.0521  -0.8154    -0.6857
PLT  22 -0.5260 -1.0041 -0.5260 0.0000 -0.7251 -0.4739  -1.7144    -1.8932
QT   22  0.1991 -0.2790  0.1991 0.7251  0.0000  0.2512  -0.7880    -0.8359
TA   22 -0.0521 -0.5303 -0.0521 0.4739 -0.2512  0.0000  -0.9836    -1.0259
     ci.lb.HT ci.lb.PLT ci.lb.QT ci.lb.TA ci.ub.AT ci.ub.BPTB ci.ub.HT
AT    -0.8154   -0.6624  -1.1862  -0.8793   0.0000     0.3633   0.8154
BPTB   0.2706    0.1151  -0.2779   0.0346   1.3196     0.0000   0.6857
HT     0.0000   -0.3385  -0.7554  -0.3980   0.8154    -0.2706   0.0000
PLT   -1.3905    0.0000  -1.7531  -1.4485   0.6624    -0.1151   0.3385
QT    -0.3572   -0.3029   0.0000  -0.4644   1.1862     0.2779   0.7554
TA    -0.5023   -0.5008  -0.9668   0.0000   0.8793    -0.0346   0.3980
     ci.ub.PLT ci.ub.QT ci.ub.TA pval.AT pval.BPTB pval.HT pval.PLT pval.QT
AT      1.7144   0.7880   0.9836     NaN    0.2654  1.0000   0.3857  0.6926
BPTB    1.8932   0.8359   1.0259  0.2654       NaN  0.0000   0.0268  0.3261
HT      1.3905   0.3572   0.5023  1.0000    0.0000     NaN   0.2330  0.4829
PLT     0.0000   0.3029   0.5008  0.3857    0.0268  0.2330      NaN  0.1668
QT      1.7531   0.0000   0.9668  0.6926    0.3261  0.4829   0.1668     NaN
TA      1.4485   0.4644   0.0000  0.9127    0.0360  0.8205   0.3406  0.4914
     pval.TA
AT    0.9127
BPTB  0.0360
HT    0.8205
PLT   0.3406
QT    0.4914
TA       NaN
      k TE.BPTB   TE.HT  TE.PLT   TE.QT  TE.TA ci.lb.BPTB ci.lb.HT ci.lb.PLT
BPTB 34  0.0000  0.2698  0.5076  0.3743 1.2598     0.0000   0.1898    0.1988
HT   34 -0.2698  0.0000  0.2378  0.1044 0.9900    -0.3499   0.0000   -0.0605
PLT  34 -0.5076 -0.2378  0.0000 -0.1334 0.7522    -0.8165  -0.5361    0.0000
QT   34 -0.3743 -0.1044  0.1334  0.0000 0.8856    -0.5943  -0.3207   -0.2351
TA   34 -1.2598 -0.9900 -0.7522 -0.8856 0.0000    -1.7853  -1.5094   -1.3512
     ci.lb.QT ci.lb.TA ci.ub.BPTB ci.ub.HT ci.ub.PLT ci.ub.QT ci.ub.TA
BPTB   0.1542   0.7343     0.0000   0.3499    0.8165   0.5943   1.7853
HT    -0.1119   0.4706    -0.1898   0.0000    0.5361   0.3207   1.5094
PLT   -0.5018   0.1533    -0.1988   0.0605    0.0000   0.2351   1.3512
QT     0.0000   0.3229    -0.1542   0.1119    0.5018   0.0000   1.4482
TA    -1.4482   0.0000    -0.7343  -0.4706   -0.1533  -0.3229   0.0000
     pval.BPTB pval.HT pval.PLT pval.QT pval.TA
BPTB       NaN  0.0000   0.0013  0.0009  0.0000
HT      0.0000     NaN   0.1182  0.3440  0.0002
PLT     0.0013  0.1182      NaN  0.4781  0.0138
QT      0.0009  0.3440   0.4781     NaN  0.0020
TA      0.0000  0.0002   0.0138  0.0020     NaN

[[1]]
      k TE.BPTB   TE.HT  TE.PLT   TE.QT  TE.TA ci.lb.BPTB ci.lb.HT ci.lb.PLT
BPTB 25  0.0000  0.3601  0.5800  0.5326 0.7234     0.0000   0.1215    0.0519
HT   25 -0.3601  0.0000  0.2198  0.1725 0.3633    -0.5988   0.0000   -0.2512
PLT  25 -0.5800 -0.2198  0.0000 -0.0473 0.1434    -1.1080  -0.6909    0.0000
QT   25 -0.5326 -0.1725  0.0473  0.0000 0.1908    -0.8538  -0.4633   -0.5062
TA   25 -0.7234 -0.3633 -0.1434 -0.1908 0.0000    -1.3482  -0.9406   -0.8886
     ci.lb.QT ci.lb.TA ci.ub.BPTB ci.ub.HT ci.ub.PLT ci.ub.QT ci.ub.TA
BPTB   0.2115   0.0987     0.0000   0.5988    1.1080   0.8538   1.3482
HT    -0.1183  -0.2141    -0.1215   0.0000    0.6909   0.4633   0.9406
PLT   -0.6009  -0.6017    -0.0519   0.2512    0.0000   0.5062   0.8886
QT     0.0000  -0.4557    -0.2115   0.1183    0.6009   0.0000   0.8372
TA    -0.8372   0.0000    -0.0987   0.2141    0.6017   0.4557   0.0000
     pval.BPTB pval.HT pval.PLT pval.QT pval.TA
BPTB       NaN  0.0031   0.0313  0.0012  0.0232
HT      0.0031     NaN   0.3604  0.2450  0.2175
PLT     0.0313  0.3604      NaN  0.8669  0.7060
QT      0.0012  0.2450   0.8669     NaN  0.5630
TA      0.0232  0.2175   0.7060  0.5630     NaN

[[2]]
      k   TE.AT TE.BPTB   TE.HT TE.PLT   TE.QT   TE.TA ci.lb.AT ci.lb.BPTB
AT   32  0.0000 -0.5578 -0.2760 0.1094 -0.0568  0.0982   0.0000    -1.3109
BPTB 32  0.5578  0.0000  0.2818 0.6672  0.5010  0.6560  -0.1953     0.0000
HT   32  0.2760 -0.2818  0.0000 0.3854  0.2192  0.3742  -0.4599    -0.4420
PLT  32 -0.1094 -0.6672 -0.3854 0.0000 -0.1662 -0.0112  -1.0247    -1.2347
QT   32  0.0568 -0.5010 -0.2192 0.1662  0.0000  0.1550  -0.7347    -0.7998
TA   32 -0.0982 -0.6560 -0.3742 0.0112 -0.1550  0.0000  -0.9813    -1.1699
     ci.lb.HT ci.lb.PLT ci.lb.QT ci.lb.TA ci.ub.AT ci.ub.BPTB ci.ub.HT
AT    -1.0119   -0.8060  -0.8483  -0.7849   0.0000     0.1953   0.4599
BPTB   0.1217    0.0997   0.2022   0.1421   1.3109     0.0000   0.4420
HT     0.0000   -0.1591  -0.0723  -0.1141   1.0119    -0.1217   0.0000
PLT   -0.9298    0.0000  -0.7837  -0.7425   0.8060    -0.0997   0.1591
QT    -0.5106   -0.4513   0.0000  -0.4136   0.8483    -0.2022   0.0723
TA    -0.8625   -0.7201  -0.7236   0.0000   0.7849    -0.1421   0.1141
     ci.ub.PLT ci.ub.QT ci.ub.TA pval.AT pval.BPTB pval.HT pval.PLT pval.QT
AT      1.0247   0.7347   0.9813     NaN    0.1466  0.4623   0.8149  0.8881
BPTB    1.2347   0.7998   1.1699  0.1466       NaN  0.0006   0.0212  0.0010
HT      0.9298   0.5106   0.8625  0.4623    0.0006     NaN   0.1653  0.1405
PLT     0.0000   0.4513   0.7201  0.8149    0.0212  0.1653      NaN  0.5979
QT      0.7837   0.0000   0.7236  0.8881    0.0010  0.1405   0.5979     NaN
TA      0.7425   0.4136   0.0000  0.8275    0.0123  0.1331   0.9761  0.5932
     pval.TA
AT    0.8275
BPTB  0.0123
HT    0.1331
PLT   0.9761
QT    0.5932
TA       NaN

[[3]]
      k   TE.AT TE.BPTB   TE.HT TE.PLT   TE.QT   TE.TA ci.lb.AT ci.lb.BPTB
AT   22  0.0000 -0.4781  0.0000 0.5260 -0.1991  0.0521   0.0000    -1.3196
BPTB 22  0.4781  0.0000  0.4781 1.0041  0.2790  0.5303  -0.3633     0.0000
HT   22  0.0000 -0.4781  0.0000 0.5260 -0.1991  0.0521  -0.8154    -0.6857
PLT  22 -0.5260 -1.0041 -0.5260 0.0000 -0.7251 -0.4739  -1.7144    -1.8932
QT   22  0.1991 -0.2790  0.1991 0.7251  0.0000  0.2512  -0.7880    -0.8359
TA   22 -0.0521 -0.5303 -0.0521 0.4739 -0.2512  0.0000  -0.9836    -1.0259
     ci.lb.HT ci.lb.PLT ci.lb.QT ci.lb.TA ci.ub.AT ci.ub.BPTB ci.ub.HT
AT    -0.8154   -0.6624  -1.1862  -0.8793   0.0000     0.3633   0.8154
BPTB   0.2706    0.1151  -0.2779   0.0346   1.3196     0.0000   0.6857
HT     0.0000   -0.3385  -0.7554  -0.3980   0.8154    -0.2706   0.0000
PLT   -1.3905    0.0000  -1.7531  -1.4485   0.6624    -0.1151   0.3385
QT    -0.3572   -0.3029   0.0000  -0.4644   1.1862     0.2779   0.7554
TA    -0.5023   -0.5008  -0.9668   0.0000   0.8793    -0.0346   0.3980
     ci.ub.PLT ci.ub.QT ci.ub.TA pval.AT pval.BPTB pval.HT pval.PLT pval.QT
AT      1.7144   0.7880   0.9836     NaN    0.2654  1.0000   0.3857  0.6926
BPTB    1.8932   0.8359   1.0259  0.2654       NaN  0.0000   0.0268  0.3261
HT      1.3905   0.3572   0.5023  1.0000    0.0000     NaN   0.2330  0.4829
PLT     0.0000   0.3029   0.5008  0.3857    0.0268  0.2330      NaN  0.1668
QT      1.7531   0.0000   0.9668  0.6926    0.3261  0.4829   0.1668     NaN
TA      1.4485   0.4644   0.0000  0.9127    0.0360  0.8205   0.3406  0.4914
     pval.TA
AT    0.9127
BPTB  0.0360
HT    0.8205
PLT   0.3406
QT    0.4914
TA       NaN

[[4]]
      k TE.BPTB   TE.HT  TE.PLT   TE.QT  TE.TA ci.lb.BPTB ci.lb.HT ci.lb.PLT
BPTB 34  0.0000  0.2698  0.5076  0.3743 1.2598     0.0000   0.1898    0.1988
HT   34 -0.2698  0.0000  0.2378  0.1044 0.9900    -0.3499   0.0000   -0.0605
PLT  34 -0.5076 -0.2378  0.0000 -0.1334 0.7522    -0.8165  -0.5361    0.0000
QT   34 -0.3743 -0.1044  0.1334  0.0000 0.8856    -0.5943  -0.3207   -0.2351
TA   34 -1.2598 -0.9900 -0.7522 -0.8856 0.0000    -1.7853  -1.5094   -1.3512
     ci.lb.QT ci.lb.TA ci.ub.BPTB ci.ub.HT ci.ub.PLT ci.ub.QT ci.ub.TA
BPTB   0.1542   0.7343     0.0000   0.3499    0.8165   0.5943   1.7853
HT    -0.1119   0.4706    -0.1898   0.0000    0.5361   0.3207   1.5094
PLT   -0.5018   0.1533    -0.1988   0.0605    0.0000   0.2351   1.3512
QT     0.0000   0.3229    -0.1542   0.1119    0.5018   0.0000   1.4482
TA    -1.4482   0.0000    -0.7343  -0.4706   -0.1533  -0.3229   0.0000
     pval.BPTB pval.HT pval.PLT pval.QT pval.TA
BPTB       NaN  0.0000   0.0013  0.0009  0.0000
HT      0.0000     NaN   0.1182  0.3440  0.0002
PLT     0.0013  0.1182      NaN  0.4781  0.0138
QT      0.0009  0.3440   0.4781     NaN  0.0020
TA      0.0000  0.0002   0.0138  0.0020     NaN

In [ ]:
lysholm_dat

**Network meta-analysis** for dichotomous outcomes

In [75]:
dichotomous = c("pivot_shift_1", "pivot_shift_2", "lachman_1", "lachman_2", "graft_failure")
lapply(dichotomous, sm = "OR", reference = "", network_meta_analysis)

Warning message:
"First treatment used as reference as argument 'reference.group' is unspecified."
Warning message:
"First treatment used as reference as argument 'reference.group' is unspecified."
Warning message:
"No comparisons selected with argument 'show = both'. You could use 'show = "all" to show all comparisons."
Warning message:
"First treatment used as reference as argument 'reference.group' is unspecified."
Warning message:
"No comparisons selected with argument 'show = both'. You could use 'show = "all" to show all comparisons."
Warning message:
"First treatment used as reference as argument 'reference.group' is unspecified."
Warning message:
"No comparisons selected with argument 'show = both'. You could use 'show = "all" to show all comparisons."
Warning message:
"First treatment used as reference as argument 'reference.group' is unspecified."

[[1]]
NULL

[[2]]
NULL

[[3]]
NULL

[[4]]
NULL

[[5]]
NULL